# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirestoreCli < Formula
  desc "firestore command line interface to work with googles firestore database"
  homepage "https://github.com/Ion-manden/firestore-cli"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.3/firestore-cli_1.1.3_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "bc53635769a157c39863bcb14d206fad874bab1ab098d5f94dcc542e4c7cb1d8"

      def install
        bin.install "firestore-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.3/firestore-cli_1.1.3_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "813fa9823008cb0bef1bfa850a0bf58c0860827756b1e8d88ed65e22580f4914"

      def install
        bin.install "firestore-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.3/firestore-cli_1.1.3_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "84245582ddafe6d7ed5c140a2c53f8d248882ea78425be4bbc2ccbaba372707d"

      def install
        bin.install "firestore-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.3/firestore-cli_1.1.3_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c8755a3a1e2f5716f052b7ccd318f655b3a0437531d03a6b3a82b2573cd55e06"

      def install
        bin.install "firestore-cli"
      end
    end
  end

  def caveats; <<~EOS
    Refer to README or documentation on the github page
  EOS
  end
end
