# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirestoreCli < Formula
  desc "firestore command line interface to work with googles firestore database"
  homepage "https://github.com/Ion-manden/firestore-cli"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.2/firestore-cli_1.1.2_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "38820c2ccb62c4c8e498f3ea60858be149080092deacbd69ea0ebe231b4ea234"

      def install
        bin.install "firestore-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.2/firestore-cli_1.1.2_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e56a3b04d38cd9be0e9b1fdfc1778627914bd9348b03cc3a280757bb4bec2ede"

      def install
        bin.install "firestore-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.2/firestore-cli_1.1.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e6952954e10d7c2e4ad45386994c93da698f8f8b473e800a75512acbc4c59199"

      def install
        bin.install "firestore-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.2/firestore-cli_1.1.2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "43b34cb02c3ce6a097f07dd1122432d1a3ebb25e7a0c0b995464f3c3f2ef9970"

      def install
        bin.install "firestore-cli"
      end
    end
  end

  def caveats; <<~EOS
    Refer to README or documentation on the github page
  EOS
  end
end
